/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/customers': RouteRecordInfo<
      '/customers',
      '/customers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inbox': RouteRecordInfo<
      '/inbox',
      '/inbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | '/settings/'
      | '/settings/members'
      | '/settings/notifications'
      | '/settings/security'
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/members': RouteRecordInfo<
      '/settings/members',
      '/settings/members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/notifications': RouteRecordInfo<
      '/settings/notifications',
      '/settings/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/security': RouteRecordInfo<
      '/settings/security',
      '/settings/security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/customers.vue': {
      routes:
        | '/customers'
      views:
        | never
    }
    'src/pages/inbox.vue': {
      routes:
        | '/inbox'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
        | '/settings/'
        | '/settings/members'
        | '/settings/notifications'
        | '/settings/security'
      views:
        | 'default'
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    'src/pages/settings/members.vue': {
      routes:
        | '/settings/members'
      views:
        | never
    }
    'src/pages/settings/notifications.vue': {
      routes:
        | '/settings/notifications'
      views:
        | never
    }
    'src/pages/settings/security.vue': {
      routes:
        | '/settings/security'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
